#!/usr/bin/env bash
# This script creates a new hosts file with modified entries for localhost and facebook.com
# It then replaces the original hosts file with the new one to change the IP resolutions
# Be cautious when running this script, as it permanently changes the IP resolutions
# Revert the changes manually by editing the /etc/hosts file if needed

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
