#!/usr/bin/env bash
# Display all active IPv4 addresses on the machine
# Uses the ip command to list IPv4 addresses, then filters and extracts the IP address part
ip -4 addr show | awk '/inet / {print $2}' | cut -d '/' -f 1

